### ISSUE TITLE
Port already in use, because proxy keeps binding to the wrong container IP

### ISSUE THREAD

**Issue by robertgzr** [balena-os/balena-engine#272]
the device had a service that was trying to bind to port `80` on the host. the engine would fail container creation with `0.0.0.0:80 already allocated`.

a `balena-proxy` process was running tied to a container IP that was used by a different service than the one we would expect

removing the libnetwork state, `ip link remove supervisor0`, removing the containers and restarting the engine fixed it.

**Comment by robertgzr** [comment]
https://github.com/moby/libnetwork/issues/1790 sounds related

**Comment by inwenc** [comment]
I did a normal `balena push` on the dummy-app repo (react/express), It did work on Josh's end to open in public URL, but not on my end, with the exact code. Then I changed the Docker compose file to map FE from 3000:3000 to 80:3000. It still showed the following error
![image](https://user-images.githubusercontent.com/53130953/151075170-d4251949-4f33-4285-980d-5c677765bec7.png)

**Comment by cywang117** [comment]
@inwenc The comment above doesn't really show the connection between your error and the issue described here. What's Josh's app? What's your app? Link to code for both? Differences between both? In this [Flowdock thread](https://www.flowdock.com/app/rulemotion/balenalabs/threads/qWyBERqlMwAnmhJob8K9fzzQArc) I commented some steps for documenting your observation of this issue here. I also included some device logs with the command I used. Could you provide more info please
